#!/bin/sh

###################################################
# Recived Parameters
###################################################
# http://manpages.ubuntu.com/manpages/zesty/man8/dhcpcd-run-hooks.8.html
# $reason='BOUND'
# $interface='wan0'
# $new_ip_address='192.168.175.180'
# $new_host_name='WEBSERVER-1'
# $new_network_number='192.168.175.0'
# $new_subnet_mask='255.255.255.0'
# $new_broadcast_address='192.168.175.255'
# $new_routers='192.168.175.5'
# $new_domain_name='lan'
# $new_domain_name_servers='192.168.175.5'
# $old_ip_address='192.168.175.180'
# $old_host_name='WEBSERVER-1'
# $old_network_number='192.168.175.0'
# $old_subnet_mask='255.255.255.0'
# $old_broadcast_address='192.168.175.255'
# $old_routers='192.168.175.5'
# $old_domain_name='lan'
# $old_domain_name_servers='192.168.175.5'
###################################################

###################################################
# Start Functions
###################################################

mask2cdr ()
{
   # Assumes there's no "255." after a non-255 byte in the mask
   local x=${1##*255.}
   set -- 0^^^128^192^224^240^248^252^254^ $(( (${#1} - ${#x})*2 )) ${x%%.*}
   x=${1%%$3*}
   echo $(( $2 + (${#x}/4) ))
}


cdr2mask ()
{
   # Number of args to shift, 255..255, first non-255 byte, zeroes
   set -- $(( 5 - ($1 / 8) )) 255 255 255 255 $(( (255 << (8 - ($1 % 8))) & 255 )) 0 0 0
   [ $1 -gt 1 ] && shift $1 || shift
   echo ${1-0}.${2-0}.${3-0}.${4-0}
}

###################################################
# End Functions
###################################################


###################################################
# Passed Parameters to SYSVARS directory
###################################################
# ${IF}-local: Local IP
# ${IF}-prefix: Prefix
# ${IF}-gateway: Gateway IP
# ${IF}-dns: DNS Servers
###################################################

IPTV_ZONE_FILE=/opt/dnsmasq.iptv

forwardZones=" \
	iptv.bell.ca \
	iptv.microsoft.com \
"

# Set SYSVARS path
SYSVARS=/tmp/sysvars
[ -d $SYSVARS ] || mkdir -p $SYSVARS

# new_routers being dropped by another hook
GATEWAY=$(grep routers /var/lib/dhcp/dhclient.eth0.36.leases | tail -n 1 | sed 's/.*routers \(.*\);/\1/')

case "$interface" in

	eth0.36)

		# add iptv route
		ip route add 10.0.0.0/8 via $GATEWAY dev eth0.36 2>/dev/null

		# Write vars to SYSVARS dir
		[ ! -z "$new_ip_address" ] && echo "$new_ip_address" > ${SYSVARS}/iptv-local
		[ ! -z "$GATEWAY" ] && echo "$GATEWAY" > ${SYSVARS}/iptv-gateway
		[ ! -z "$new_subnet_mask" ] && echo "${new_network_number}/$(mask2cdr ${new_subnet_mask})" > ${SYSVARS}/iptv-prefix
		[ ! -z "$new_domain_name_servers" ] && echo "$new_domain_name_servers" > ${SYSVARS}/iptv-dns

		echo "# Dynamically generated file - DO NOT EDIT" > $IPTV_ZONE_FILE
		echo >> $IPTV_ZONE_FILE
		
		for forwardZone in $forwardZones; do
			for new_domain_name_server in $new_domain_name_servers; do
				echo "server=/${forwardZone}/${new_domain_name_server}"  >> $IPTV_ZONE_FILE
			done
		done
		echo >> $IPTV_ZONE_FILE
		
#		service igmpproxy restart
		;;
         

esac


###################################################
# End sysvars
###################################################


exit 0